---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-json
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: 515f543f5718ebfd6ce22e16708bb32c68ff96e1 # frozen: v3.8.3
    hooks:
      - id: prettier

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: ea2eb407b4cbce87cf0d502f36578950494f5ac9 # frozen: v1.23.1
    hooks:
      - id: zizmor

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: d0e12caebb2ab0ee8bf98181c8bfe9702bca103d # frozen: v1.105.0
    hooks:
      - id: terraform_fmt
        args:
          - --hook-config=--tf-path=tofu
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --hook-config=--delegate-chdir --tf-path=tofu
