[tool.poetry]
name = "infra"
version = "0.1.0"
description = "Infrastructure"
authors = ["Andrew Clemons <andrew.clemons@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"
ansible = "9.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
