[tool.poetry]
name = "infra"
version = "0.1.0"
description = "Infrastructure"
authors = ["Andrew Clemons <andrew.clemons@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.0"
ansible = "8.5.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "3.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
