---
# tasks file for slackroll
- name: Check if slackroll is installed.
  shell: ls /var/lib/pkgtools/packages/slackroll-*
  changed_when: false
  register: slackroll_install_status
  failed_when: "slackroll_install_status.rc not in [ 0, 2 ]"

- name: Download slackroll (arm)
  ansible.builtin.get_url:
    url: "{{ slackroll_caffe_pkg_repo }}/system/slackroll/slackroll-v51-noarch-1_slack15.0acl.txz"
    dest: /tmp/slackroll-v51-noarch-1_slack15.0acl.txz
    checksum: "{{ 'md5:6318aeb68c9c1d4e0880c001d5810c1d' if ansible_architecture == 'armv7l' else 'md5:cee9faa99476ff9315685d035408c914' }}"
  when:
    - slackroll_install_status.rc != 0

- name: Install slackroll
  shell: |
    installpkg /tmp/slackroll-v51-noarch-1_slack15.0acl.txz
    rm /tmp/slackroll-v51-noarch-1_slack15.0acl.txz
  when:
    - slackroll_install_status.rc != 0
  become: true

- name: Ensure slackroll directory exists
  file:
    path: /var/slackroll
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Configure slackroll primary mirror.
  copy:
    dest: "/var/slackroll/mirror"
    content: |
      {{ slackroll_mirror }}
  become: true

- name: install slackware gpg key
  gpg_key:
    gpgbin: /usr/bin/gpg2
    fpr: EC5649DA401E22ABFA6736EF6A4463C040102233
    keyserver: eu.pool.sks-keyservers.net
  become: true

- name: Gather blacklist.
  shell: |
    slackroll batch print-blacklist | sed '1d;$d' | sed 's/^[[:space:]]*[[:digit:]][[:digit:]]*[[:space:]]*//'
  changed_when: false
  register: slackroll_blacklist
  become: true

- name: Blacklist /testing.
  shell: |
    slackroll batch blacklist-add '^\./testing.*'
  when:
    - "'^\\./testing.*' not in slackroll_blacklist.stdout"
  become: true

- name: Gather repos.
  shell: |
    slackroll batch list-repos | sed '1d;$d' | sed 's/^[[:space:]]*[[:digit:]][[:digit:]]*[[:space:]]*//'
  changed_when: false
  register: slackroll_repos
  become: true

- name: Add caffe pkg repo.
  shell: |
    slackroll batch add-repo '{{ slackroll_caffe_pkg_repo }}'
  when:
    - "slackroll_caffe_pkg_repo | string not in slackroll_repos.stdout"
  become: true

- name: install caffe gpg key
  gpg_key:
    gpgbin: /usr/bin/gpg2
    fpr: 217C7228C48DC5FF2C876E3ACD26380FFACBDA2B
    keyserver: eu.pool.sks-keyservers.net
  become: true

- name: Add AlienBOB's sbrepo.
  shell: |
    slackroll batch add-repo '{{ slackroll_alien_sbrepo }}'
  when:
    - slackroll_alien_sbrepo_enabled | bool
    - "slackroll_alien_sbrepo | string not in slackroll_repos.stdout"
  become: true

- name: install caffe gpg key
  gpg_key:
    gpgbin: /usr/bin/gpg2
    fpr: F2CE1B92EE1F2C0CE97E581E5E56AAAFA75CBDA0
    keyserver: eu.pool.sks-keyservers.net
  when:
    - slackroll_alien_sbrepo_enabled | bool
  become: true

- name: Limit AlienBOB's packages.
  shell: |
    slackroll batch blacklist-add '^\.\/(?!chromium|libreoffice|vlc).*$@\/sbrepos\/'
  when:
    - slackroll_alien_sbrepo_enabled | bool
    - "'^\\.\\/(?!chromium|libreoffice|vlc).*$@\\/sbrepos\\/' not in slackroll_blacklist.stdout"
  become: true

- name: Add AlienBOB's restricted sbrepo.
  shell: |
    slackroll batch add-repo '{{ slackroll_alien_restricted_sbrepo }}'
  when:
    - slackroll_alien_restricted_sbrepo_enabled | bool
    - "slackroll_alien_restricted_sbrepo | string not in slackroll_repos.stdout"
  become: true

- name: Add AlienBOB's multilib.
  shell: |
    slackroll batch add-repo '{{ slackroll_alien_multilib_repo }}'
  when:
    - slackroll_alien_multilib_enabled | bool
    - "slackroll_alien_multilib_repo | string not in slackroll_repos.stdout"
  become: true

- name: Blacklist non-multilib glibc packages.
  shell: |
    slackroll batch blacklist-add 'glibc-(?!zoneinfo)@^(?!http)'
  when:
    - slackroll_alien_multilib_enabled | bool
    - "'glibc-(?!zoneinfo)@^(?!http)' not in slackroll_blacklist.stdout"
  become: true

- name: Add sarpi caffe repo.
  shell: |
    slackroll batch add-repo '{{ slackroll_caffe_sarpi_pkg_repo }}'
  when:
    - ansible_architecture == 'armv7l'
    - "slackroll_caffe_sarpi_pkg_repo | string not in slackroll_repos.stdout"
  become: true
